config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :writing_exercises
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :writing_exercise
end

app/models/writing_exercise.rb
class WritingExercise < ApplicationRecord
    has_many :comments
    
    validates :duration_in_minutes, :category, :prompt, :output, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_path, status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.expect(comment: [ :writing_exercise_id, :content ])
    end
end

app/controllers/writing_exercises_controller.rb
class WritingExercisesController < ApplicationController
  before_action :set_writing_exercise, only: %i[ show edit update destroy ]

  # GET /writing_exercises or /writing_exercises.json
  def index
    @writing_exercises = WritingExercise.all
  end

  # GET /writing_exercises/1 or /writing_exercises/1.json
  def show
  end

  # GET /writing_exercises/new
  def new
    @writing_exercise = WritingExercise.new
  end

  # GET /writing_exercises/1/edit
  def edit
  end

  # POST /writing_exercises or /writing_exercises.json
  def create
    @writing_exercise = WritingExercise.new(writing_exercise_params)

    respond_to do |format|
      if @writing_exercise.save
        format.html { redirect_to @writing_exercise, notice: "Writing exercise was successfully created." }
        format.json { render :show, status: :created, location: @writing_exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @writing_exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writing_exercises/1 or /writing_exercises/1.json
  def update
    respond_to do |format|
      if @writing_exercise.update(writing_exercise_params)
        format.html { redirect_to @writing_exercise, notice: "Writing exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @writing_exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @writing_exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writing_exercises/1 or /writing_exercises/1.json
  def destroy
    @writing_exercise.destroy!

    respond_to do |format|
      format.html { redirect_to writing_exercises_path, status: :see_other, notice: "Writing exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writing_exercise
      @writing_exercise = WritingExercise.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def writing_exercise_params
      params.expect(writing_exercise: [ :duration_in_minutes, :category, :prompt, :output ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/writing_exercises_helper.rb
module WritingExercisesHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Writing exercise:</strong>
    <%= comment.writing_exercise_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= comment.content %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul class="list-disc ml-6">
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :writing_exercise_id %>
    <%= form.text_field :writing_exercise_id, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": comment.errors[:writing_exercise_id].none?, "border-red-400 focus:outline-red-600": comment.errors[:writing_exercise_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.textarea :content, rows: 4, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": comment.errors[:content].none?, "border-red-400 focus:outline-red-600": comment.errors[:content].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Show this comment", @comment, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/comments/index.html.erb
<% content_for :title, "Comments" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>
    <%= link_to "New comment", new_comment_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="comments" class="min-w-full">
    <% if @comments.any? %>
      <% @comments.each do |comment| %>
        <%= render comment %>
        <p>
          <%= link_to "Show this comment", comment, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No comments found.</p>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/comments/show.html.erb
<% content_for :title, "Showing comment" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing comment</h1>

  <%= render @comment %>

  <%= link_to "Edit this comment", edit_comment_path(@comment), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this comment", @comment, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Writing Exercises" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/writing_exercises/_form.html.erb
<%= form_with(model: writing_exercise) do |form| %>
  <% if writing_exercise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(writing_exercise.errors.count, "error") %> prohibited this writing_exercise from being saved:</h2>

      <ul>
        <% writing_exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :duration_in_minutes, style: "display: block" %>
    <%= form.number_field :duration_in_minutes %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :prompt, style: "display: block" %>
    <%= form.text_field :prompt %>
  </div>

  <div>
    <%= form.label :output, style: "display: block" %>
    <%= form.textarea :output %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/writing_exercises/_writing_exercise.html.erb
<div id="<%= dom_id writing_exercise %>">
  <h2 class="text-lg font-bold"><%= writing_exercise.prompt %></h2>
  <p>
    <strong>Created:</strong>
    <%= writing_exercise.created_at.strftime("%b %d %Y") %>
  </p>

  <p>
    <strong>Duration in minutes:</strong>
    <%= writing_exercise.duration_in_minutes %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= writing_exercise.category %>
  </p>

  <p>
    <strong>Output:</strong>
    <%= writing_exercise.output %>
  </p>
</div>

app/views/writing_exercises/edit.html.erb
<% content_for :title, "Editing writing exercise" %>

<h1>Editing writing exercise</h1>

<%= render "form", writing_exercise: @writing_exercise %>

<br>

<div>
  <%= link_to "Show this writing exercise", @writing_exercise %> |
  <%= link_to "Back to writing exercises", writing_exercises_path %>
</div>

app/views/writing_exercises/index.html.erb
<div id="writing_exercises">
<p style="color: green"><%= notice %></p>

<% content_for :title, "Writing exercises" %>

<h1>Writing exercises</h1>
  <ul class="grid grid-cols-1">
    <% @writing_exercises.each do |writing_exercise| %>
      <li class="bg-white shadow-md hover:bg-gray-100 rounded py-4 px-6">
        <%= render writing_exercise %>
        <p>
          <%= link_to "Show this writing exercise", writing_exercise %>
        </p>
      </li>
    <% end %>
  </ul>

<%= link_to "New writing exercise", new_writing_exercise_path %>

</div>

app/views/writing_exercises/new.html.erb
<% content_for :title, "New writing exercise" %>

<h1>New writing exercise</h1>

<%= render "form", writing_exercise: @writing_exercise %>

<br>

<div>
  <%= link_to "Back to writing exercises", writing_exercises_path %>
</div>

app/views/writing_exercises/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @writing_exercise %>

<div>
  <%= link_to "Edit this writing exercise", edit_writing_exercise_path(@writing_exercise) %> |
  <%= link_to "Back to writing exercises", writing_exercises_path %>

  <%= button_to "Destroy this writing exercise", @writing_exercise, method: :delete %>
</div>